### ISSUE TITLE
many-to-many relationship

### ISSUE THREAD

**Issue by merlin2049er** [merlin2049er/MD-APP#4]
I established a many-to-many relationship between the users and products.  I haven't really tested this, but I would imaging by pressing the add to cart button on my products page it would create a record here to map who is joining the campaign for that product.    I need to code this.  I think I should add a timestamp to this record to to determine when they have joined.

**Comment by medright** [comment]
Just a quick look, line 9 of the user.rb file needs to be pleural so :products .. time stamps happen by default whenever a record is created.. you can call it in your views for objects by calling the object_name.created_at syntax

**Comment by medright** [comment]
After looking at this a bit, are you sure you want many to many between users and products? this would allow a product to have more than one user.. I can see a one to many relationship between users and products.. maybe I'm not sure of what the goal is in the app here..
