### ISSUE TITLE
rake task populator

### ISSUE THREAD

**Issue by merlin2049er** [merlin2049er/MD-APP#5]
I have a rake task under lib/tasks called populate.rake.   I would love to run this on heroku and populate the products and categories with some fake data.

**Comment by medright** [comment]
whatever rake command you use to run it on your local machine you can use on heroku, just add the heroku command to the rake command. The link I posted under the other issue for rake on heroku should give you the info you need.

**Comment by merlin2049er** [comment]
ok, went back to the gem and found the task to run...
rake db:populate
heroku rake db:populate

**Comment by medright** [comment]
Awesome.
