### ISSUE TITLE
My contacts table is not on heroku.

### ISSUE THREAD

**Issue by merlin2049er** [merlin2049er/MD-APP#7]
contacts form works great in development, but fails in production.  I need to create a table on heroku.

**Comment by merlin2049er** [comment]
can't run rake db:migrate on heroku? what's wrong with my schema? I can't add a new table I created. I get stuck here...

SELECT "schema_migrations".* FROM "schema_migrations"
Migrating to ChangeDataTypeForFieldname (20161014185102)
   (0.4ms)  BEGIN
== 20161014185102 ChangeDataTypeForFieldname: migrating =======================
-- change_table(:products)
   (1.0ms)  ALTER TABLE "products" ALTER COLUMN "price" TYPE decimal(8,2)
   (0.4ms)  ROLLBACK
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DatatypeMismatch: ERROR:  column "price" cannot be cast automatically to type numeric
HINT:  You might need to specify "USING price::numeric(8,2)".
: ALTER TABLE "products" ALTER COLUMN "price" TYPE decimal(8,2)

**Comment by medright** [comment]
Yes you can run rake: https://devcenter.heroku.com/articles/rake

And also, if you couldn't run rake you wouldn't have even got this error.. I'll pull the code and do a push to heroku to test later..but maybe if you're trying to change an existing column that has data in it already you need to run reset your db before running rake.. the bottom of the article talks about this a bit..

**Comment by medright** [comment]
I've downloaded and installed the app on my local machine, the issue is with your current db structure and a conflict with the type you changed it to. Just reset your heroku db and then run rake db:migrate again.

**Comment by merlin2049er** [comment]
ok , contacts form and table are there.  just checking to see if it actually sends an email.

**Comment by merlin2049er** [comment]
nope, got to fix mailer form, it isn't doing anything.  lol.

**Comment by merlin2049er** [comment]
Yes, it's working
